# Site settings
title: Musings of an Enlightened Idiot
subtitle: by HTML5 UP
email: gauthamv.529@gmail.com
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Toronto
state: ON
zip_code: 
country: Canada
phone:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/gauthamvasan
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/gauthamvasan/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
